### ISSUE TITLE
Admin tool to remove incorrectly reported research

### ISSUE THREAD

**Issue by tehstone** [KyogreBot/Kyogre#51]
Raids can be marked as `!duplicate` either by admins or by any user. But there is no way to remove a research task once reported. Allowing it through the Listing channel would be messy, but it may at times be difficult to scroll back and find the correct report in the Reporting channel. Without adding some sort of ID per report, there may be no easier way.

For now, I would recommend allowing it to be admin only since our anti-abuse tools are minimal.

**Comment by klords** [comment]
moving to 1.1 milestone

**Comment by tehstone** [comment]
Kyogre should add an emoji response to each research report. If the user who reported, or an admin selects that emoji then the report will be removed.

**Comment by tehstone** [comment]
This has been implemented
